### ISSUE TITLE
Version 1.0.4 not released on npmjs.com

### ISSUE THREAD

**Issue by lucasnetau** [routablehq/jest-scss-transform#11]
**Describe the bug**

Current version is 1.0.3 https://www.npmjs.com/package/jest-scss-transform?activeTab=versions 

This version is missing commit https://github.com/routablehq/jest-scss-transform/commit/18bfaf4518d7f98c679246eb34cc22969f996697 which allows it to work with higher babel-jest versions. 

**Expected behavior**

npmjs packages show the same release version as per github

**Comment by bvogel** [comment]
Hi, any chance to get this adjusted?

**Comment by tomharel** [comment]
> Hi, any chance to get this adjusted?

Apologies for the delay. This is now published.
